# -*- coding: utf-8 -*-
"""Iris_Clustering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YZReAZVtWPV7WxFZxzFjlZeLOEQTqOOk
"""

import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.datasets import load_iris
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans, AgglomerativeClustering
from sklearn.decomposition import PCA
from sklearn.metrics import silhouette_score

sns.set_theme(style="whitegrid")

OUTPUT_DIR = "week3_clustering_outputs"
os.makedirs(OUTPUT_DIR, exist_ok=True)

print("=" * 75)
print("WEEK 3 - UNSUPERVISED LEARNING AND CLUSTERING")
print("=" * 75)


# ============================================================
# 1. LOAD PUBLIC DATASET
# ============================================================

iris = load_iris()

X = pd.DataFrame(
    iris.data,
    columns=iris.feature_names
)

# Known labels are kept only for post-clustering interpretation.
y = pd.Series(
    iris.target,
    name="Species"
)

species_names = {
    0: "setosa",
    1: "versicolor",
    2: "virginica"
}

df = X.copy()
df["Species"] = y.map(species_names)

print("\nDataset shape:", df.shape)
print("\nFirst five records:")
print(df.head())

print("\nDataset information:")
print(df.info())

print("\nDescriptive statistics:")
print(df.describe())


# ============================================================
# 2. INITIAL DATA QUALITY CHECK
# ============================================================

print("\n" + "=" * 75)
print("1. DATA QUALITY CHECK")
print("=" * 75)

print("\nMissing values:")
print(df.isnull().sum())

print("\nDuplicate rows:", df.duplicated().sum())

# Remove exact duplicates only if they exist.
df_model = df.drop_duplicates().copy()

feature_columns = iris.feature_names

print("\nFeatures used for clustering:")
for feature in feature_columns:
    print("-", feature)


# ============================================================
# 3. PREPROCESSING / STANDARDIZATION
# ============================================================

print("\n" + "=" * 75)
print("2. PREPROCESSING")
print("=" * 75)

scaler = StandardScaler()

X_scaled = scaler.fit_transform(
    df_model[feature_columns]
)

X_scaled_df = pd.DataFrame(
    X_scaled,
    columns=feature_columns
)

print("Features standardized using StandardScaler.")
print("\nStandardized feature summary:")
print(X_scaled_df.describe().round(2))


# ============================================================
# 4. CHOOSE NUMBER OF CLUSTERS - ELBOW METHOD
# ============================================================

print("\n" + "=" * 75)
print("3. SELECTING NUMBER OF CLUSTERS")
print("=" * 75)

inertias = []
k_values = range(2, 9)

for k in k_values:
    model = KMeans(
        n_clusters=k,
        random_state=42,
        n_init=10
    )
    model.fit(X_scaled)
    inertias.append(model.inertia_)

elbow_results = pd.DataFrame({
    "K": list(k_values),
    "Inertia": inertias
})

print("\nElbow results:")
print(elbow_results)

elbow_results.to_csv(
    os.path.join(
        OUTPUT_DIR,
        "elbow_results.csv"
    ),
    index=False
)

plt.figure(figsize=(8, 5))
plt.plot(
    list(k_values),
    inertias,
    marker="o"
)
plt.title("Elbow Method for Selecting K")
plt.xlabel("Number of Clusters (K)")
plt.ylabel("Within-Cluster Sum of Squares (Inertia)")
plt.xticks(list(k_values))
plt.tight_layout()

plt.savefig(
    os.path.join(
        OUTPUT_DIR,
        "01_elbow_method.png"
    ),
    dpi=200
)

plt.show()

print(
    "\nThe Iris dataset is evaluated primarily around K=3 because "
    "three natural flower groups are expected from the feature structure. "
    "The elbow and silhouette results are used as supporting evidence."
)


# ============================================================
# 5. SILHOUETTE ANALYSIS
# ============================================================

print("\n" + "=" * 75)
print("4. SILHOUETTE ANALYSIS")
print("=" * 75)

silhouette_results = []

for k in range(2, 9):
    model = KMeans(
        n_clusters=k,
        random_state=42,
        n_init=10
    )

    labels = model.fit_predict(X_scaled)

    score = silhouette_score(
        X_scaled,
        labels
    )

    silhouette_results.append({
        "K": k,
        "Silhouette Score": round(score, 4)
    })

silhouette_df = pd.DataFrame(
    silhouette_results
)

print(silhouette_df)

silhouette_df.to_csv(
    os.path.join(
        OUTPUT_DIR,
        "silhouette_results.csv"
    ),
    index=False
)

plt.figure(figsize=(8, 5))

plt.plot(
    silhouette_df["K"],
    silhouette_df["Silhouette Score"],
    marker="o"
)

plt.title("Silhouette Score by Number of Clusters")
plt.xlabel("Number of Clusters (K)")
plt.ylabel("Silhouette Score")
plt.xticks(range(2, 9))

plt.tight_layout()

plt.savefig(
    os.path.join(
        OUTPUT_DIR,
        "02_silhouette_scores.png"
    ),
    dpi=200
)

plt.show()

best_k = int(
    silhouette_df.loc[
        silhouette_df["Silhouette Score"].idxmax(),
        "K"
    ]
)

print("\nBest K according to silhouette score:", best_k)


# ============================================================
# 6. K-MEANS CLUSTERING
# ============================================================

print("\n" + "=" * 75)
print("5. K-MEANS CLUSTERING")
print("=" * 75)

# K=3 is selected for the main analysis based on the
# elbow/silhouette evaluation and the natural three-group
# structure of the Iris feature space.
K = 3

kmeans = KMeans(
    n_clusters=K,
    random_state=42,
    n_init=10
)

df_model["KMeans_Cluster"] = kmeans.fit_predict(
    X_scaled
)

kmeans_silhouette = silhouette_score(
    X_scaled,
    df_model["KMeans_Cluster"]
)

print("Selected K:", K)
print(
    "K-Means silhouette score:",
    round(kmeans_silhouette, 4)
)

print("\nCluster counts:")
print(
    df_model["KMeans_Cluster"]
    .value_counts()
    .sort_index()
)


# ============================================================
# 7. PCA FOR 2D VISUALIZATION
# ============================================================

print("\n" + "=" * 75)
print("6. PCA VISUALIZATION")
print("=" * 75)

pca = PCA(
    n_components=2,
    random_state=42
)

X_pca = pca.fit_transform(X_scaled)

pca_df = pd.DataFrame(
    X_pca,
    columns=["PC1", "PC2"]
)

pca_df["Cluster"] = df_model[
    "KMeans_Cluster"
].values

pca_df["Species"] = df_model[
    "Species"
].values

explained = pca.explained_variance_ratio_ * 100

print(
    f"PC1 explains {explained[0]:.2f}% "
    f"of variance."
)

print(
    f"PC2 explains {explained[1]:.2f}% "
    f"of variance."
)

plt.figure(figsize=(9, 6))

sns.scatterplot(
    data=pca_df,
    x="PC1",
    y="PC2",
    hue="Cluster",
    palette="deep",
    s=80
)

plt.title("K-Means Clusters Visualized Using PCA")
plt.xlabel(
    f"Principal Component 1 ({explained[0]:.1f}% variance)"
)
plt.ylabel(
    f"Principal Component 2 ({explained[1]:.1f}% variance)"
)
plt.legend(title="Cluster")

plt.tight_layout()

plt.savefig(
    os.path.join(
        OUTPUT_DIR,
        "03_kmeans_pca_clusters.png"
    ),
    dpi=200
)

plt.show()


# ============================================================
# 8. CLUSTER PROFILE
# ============================================================

print("\n" + "=" * 75)
print("7. CLUSTER PROFILING")
print("=" * 75)

cluster_profile = (
    df_model
    .groupby("KMeans_Cluster")[feature_columns]
    .mean()
    .round(2)
)

cluster_sizes = (
    df_model["KMeans_Cluster"]
    .value_counts()
    .sort_index()
)

cluster_profile.insert(
    0,
    "Cluster Size",
    cluster_sizes
)

print("\nCluster feature means:")
print(cluster_profile)

cluster_profile.to_csv(
    os.path.join(
        OUTPUT_DIR,
        "kmeans_cluster_profile.csv"
    )
)


# ============================================================
# 9. CLUSTER VS KNOWN SPECIES - INTERPRETATION ONLY
# ============================================================

print("\n" + "=" * 75)
print("8. CLUSTER INTERPRETATION")
print("=" * 75)

cross_tab = pd.crosstab(
    df_model["KMeans_Cluster"],
    df_model["Species"]
)

print("\nCluster vs known species:")
print(cross_tab)

cross_tab.to_csv(
    os.path.join(
        OUTPUT_DIR,
        "cluster_species_crosstab.csv"
    )
)

# This is not used to train the clustering model.
# It is only used to understand what the unsupervised clusters represent.


# ============================================================
# 10. CLUSTER VISUALIZATION BY TWO ORIGINAL FEATURES
# ============================================================

plt.figure(figsize=(9, 6))

sns.scatterplot(
    data=df_model,
    x="petal length (cm)",
    y="petal width (cm)",
    hue="KMeans_Cluster",
    palette="deep",
    s=80
)

plt.title("K-Means Clusters: Petal Length vs Petal Width")
plt.xlabel("Petal Length (cm)")
plt.ylabel("Petal Width (cm)")
plt.legend(title="Cluster")

plt.tight_layout()

plt.savefig(
    os.path.join(
        OUTPUT_DIR,
        "04_clusters_petal_features.png"
    ),
    dpi=200
)

plt.show()


# ============================================================
# 11. HIERARCHICAL CLUSTERING
# ============================================================

print("\n" + "=" * 75)
print("9. HIERARCHICAL CLUSTERING")
print("=" * 75)

hierarchical = AgglomerativeClustering(
    n_clusters=3,
    linkage="ward"
)

df_model["Hierarchical_Cluster"] = (
    hierarchical.fit_predict(X_scaled)
)

hierarchical_silhouette = silhouette_score(
    X_scaled,
    df_model["Hierarchical_Cluster"]
)

print(
    "Hierarchical silhouette score:",
    round(hierarchical_silhouette, 4)
)

print("\nHierarchical cluster counts:")
print(
    df_model["Hierarchical_Cluster"]
    .value_counts()
    .sort_index()
)

# PCA visualization
plt.figure(figsize=(9, 6))

pca_h = pca_df.copy()
pca_h["Cluster"] = df_model[
    "Hierarchical_Cluster"
].values

sns.scatterplot(
    data=pca_h,
    x="PC1",
    y="PC2",
    hue="Cluster",
    palette="deep",
    s=80
)

plt.title("Hierarchical Clustering Visualized Using PCA")
plt.xlabel(
    f"PC1 ({explained[0]:.1f}% variance)"
)
plt.ylabel(
    f"PC2 ({explained[1]:.1f}% variance)"
)
plt.legend(title="Cluster")

plt.tight_layout()

plt.savefig(
    os.path.join(
        OUTPUT_DIR,
        "05_hierarchical_pca_clusters.png"
    ),
    dpi=200
)

plt.show()


# ============================================================
# 12. COMPARE CLUSTERING METHODS
# ============================================================

comparison = pd.DataFrame({
    "Algorithm": [
        "K-Means",
        "Hierarchical Agglomerative"
    ],
    "Clusters": [3, 3],
    "Silhouette Score": [
        round(kmeans_silhouette, 4),
        round(hierarchical_silhouette, 4)
    ]
})

print("\nAlgorithm comparison:")
print(comparison)

comparison.to_csv(
    os.path.join(
        OUTPUT_DIR,
        "algorithm_comparison.csv"
    ),
    index=False
)


# ============================================================
# 13. BUSINESS / RESEARCH INTERPRETATION
# ============================================================

print("\n" + "=" * 75)
print("10. INTERPRETATION")
print("=" * 75)

print("""
Cluster interpretation should be based on feature averages rather
than cluster numbers themselves. Cluster IDs are arbitrary labels.

Typical interpretation for the Iris dataset:

- One cluster is strongly characterized by smaller petal dimensions.
- The remaining clusters have larger petal dimensions and may be
  separated mainly by petal length, petal width, and related measurements.
- The clusters demonstrate that unsupervised learning can discover
  structure without using species labels during training.

Potential research implication:
The approach can be used as an exploratory method to discover natural
groups before applying supervised classification or statistical testing.

Potential business implication:
The same clustering workflow can be adapted to customer segmentation,
product grouping, risk profiling, or behavioral segmentation where
predefined labels are unavailable.
""")


# ============================================================
# 14. SAVE FINAL CLUSTERED DATASET
# ============================================================

final_file = os.path.join(
    OUTPUT_DIR,
    "iris_clustered.csv"
)

df_model.to_csv(
    final_file,
    index=False
)

print("\nFinal clustered dataset saved to:")
print(final_file)


# ============================================================
# 15. FINAL SUMMARY
# ============================================================

print("\n" + "=" * 75)
print("FINAL SUMMARY")
print("=" * 75)

print("Dataset: Iris")
print("Clustering features:", len(feature_columns))
print("Selected K:", K)
print(
    "K-Means silhouette:",
    round(kmeans_silhouette, 4)
)
print(
    "Hierarchical silhouette:",
    round(hierarchical_silhouette, 4)
)
print("Output directory:", OUTPUT_DIR)

print("\nClustering analysis completed successfully.")